---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: https://dev82381.service-now.com

    - name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents
      ansible.builtin.uri:
        url: https://dev82381.service-now.com
        return_content: yes
      register: this
      failed_when: "'AWESOME' not in this.content"