---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    snow_change_id: CHG0002001
    org: Default
    check_ssl: no
    sn_instance: "kdcademo5"
    sn_username: "sunil.soman"
    sn_password: "Chenai101chenai"
    uri: "https://{{ sn_instance }}.service-now.com/api/now/table"
    location_bdc_cities: []
    location_soc_cities: []
    bdc: []
    soc: []
    host_statuses:
      - installed
    python_interpreter: /usr/bin/python2.7

  pre_tasks:
   - setup:
      gather_subset:
       - '!all'
  
  tasks:
    - name: Get ServiceNow Change information
      ansible.builtin.uri:
        url: "{{ uri }}/change_request?sysparm_query=number={{ snow_change_id }}"
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
      register: change_info
    
    
      debug:
      var: change_info
